included:
  - Sources
  - Tests

excluded:
  - .build
  - ExampleApp

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

disabled_rules:
  - trailing_comma
  - identifier_name

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
